server:
  port: 9400
spring:
  application:
    name: provider-message

eureka:
  instance:
    instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://eureka-server:9500/eureka,http://eureka-server1:9501/eureka
